# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='calculator',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63\x61lculator.proto\x12\ncalculator\"+\n\x07Numbers\x12\x0f\n\x07number1\x18\x01 \x01(\x03\x12\x0f\n\x07number2\x18\x02 \x01(\x03\"\x1c\n\x08\x41\x64\x64ition\x12\x10\n\x08\x61\x64\x64ition\x18\x01 \x01(\x03\x32\x42\n\x05\x41\x64\x64\x65r\x12\x39\n\nAddNumbers\x12\x13.calculator.Numbers\x1a\x14.calculator.Addition\"\x00\x42\x31\n\x1bio.grpc.examples.helloworldB\nCalculatorP\x01\xa2\x02\x03HLWb\x06proto3')
)




_NUMBERS = _descriptor.Descriptor(
  name='Numbers',
  full_name='calculator.Numbers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number1', full_name='calculator.Numbers.number1', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number2', full_name='calculator.Numbers.number2', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=75,
)


_ADDITION = _descriptor.Descriptor(
  name='Addition',
  full_name='calculator.Addition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addition', full_name='calculator.Addition.addition', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['Numbers'] = _NUMBERS
DESCRIPTOR.message_types_by_name['Addition'] = _ADDITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Numbers = _reflection.GeneratedProtocolMessageType('Numbers', (_message.Message,), dict(
  DESCRIPTOR = _NUMBERS,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.Numbers)
  ))
_sym_db.RegisterMessage(Numbers)

Addition = _reflection.GeneratedProtocolMessageType('Addition', (_message.Message,), dict(
  DESCRIPTOR = _ADDITION,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.Addition)
  ))
_sym_db.RegisterMessage(Addition)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033io.grpc.examples.helloworldB\nCalculatorP\001\242\002\003HLW'))

_ADDER = _descriptor.ServiceDescriptor(
  name='Adder',
  full_name='calculator.Adder',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=107,
  serialized_end=173,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddNumbers',
    full_name='calculator.Adder.AddNumbers',
    index=0,
    containing_service=None,
    input_type=_NUMBERS,
    output_type=_ADDITION,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADDER)

DESCRIPTOR.services_by_name['Adder'] = _ADDER

# @@protoc_insertion_point(module_scope)
