# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calculator_pb2 as calculator__pb2


class AdderStub(object):
  """The "Addition" service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddNumbers = channel.unary_unary(
        '/calculator.Adder/AddNumbers',
        request_serializer=calculator__pb2.Numbers.SerializeToString,
        response_deserializer=calculator__pb2.Addition.FromString,
        )


class AdderServicer(object):
  """The "Addition" service definition.
  """

  def AddNumbers(self, request, context):
    """Sends a addition of two numbers
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AdderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddNumbers': grpc.unary_unary_rpc_method_handler(
          servicer.AddNumbers,
          request_deserializer=calculator__pb2.Numbers.FromString,
          response_serializer=calculator__pb2.Addition.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'calculator.Adder', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
